name: we_care
description: "A new Flutter project."
publish_to: 'none'

version: 1.1.0+1

environment:
  sdk: ^3.6.0

dependencies:
  accordion: ^2.6.0
  alarm: ^5.1.2
  audioplayers: ^6.4.0
  auto_size_text: ^3.0.0
  bloc: ^9.0.0
  blur_detection: ^1.0.0
  cached_network_image: ^3.4.1
  camera: ^0.11.1
  carousel_slider: ^5.0.0
  confetti: ^0.8.0
  country_code_picker: ^3.1.0
  cupertino_icons: ^1.0.8
  curved_labeled_navigation_bar: ^2.0.5
  device_preview: ^1.2.0
  dio: ^5.7.0
  equatable: ^2.0.7
  firebase_core: ^4.0.0
  firebase_messaging: ^16.0.0
  fl_chart: ^0.70.2
  flutter:
    sdk: flutter
  flutter_bloc: ^9.0.0
  flutter_dotenv: ^6.0.0
  flutter_local_notifications: ^19.4.0
  flutter_localizations:
    sdk: flutter
  flutter_screenutil: ^5.9.3
  flutter_secure_storage: ^9.2.4
  flutter_svg: ^2.0.17
  fluttertoast: ^8.2.10
  freezed_annotation: ^2.4.4
  get_it: ^8.0.3
  google_mlkit_text_recognition: ^0.15.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  image_picker: ^1.1.2
  json_annotation: ^4.9.0
  lottie: ^3.3.1
  manual_speech_to_text: ^1.0.4
  path_provider: ^2.1.5
  permission_handler: ^11.3.1
  photo_view: ^0.15.0
  pin_code_fields: ^8.0.1
  pretty_dio_logger: ^1.4.0
  retrofit: ^4.4.2
  share_plus: ^10.1.4
  shared_preferences: ^2.4.0
  skeletonizer: ^2.1.0+1
  smooth_page_indicator: ^1.2.0+3
  speech_to_text: ^7.3.0
  timezone: ^0.10.0

dev_dependencies:
  build_runner: ^2.4.9
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  # Code generators - بديل آخر للإصدارات
  freezed: ^2.4.4
  hive_generator: ^2.0.1
  json_serializable: ^6.6.2
  retrofit_generator: ^6.0.0
  shimmer: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/images/
    - assets/svgs/
    - assets/alarm_sounds/
    - assets/sounds/

  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-Black.ttf
        - asset: assets/fonts/Cairo-Bold.ttf
        - asset: assets/fonts/Cairo-ExtraBold.ttf
        - asset: assets/fonts/Cairo-ExtraLight.ttf
        - asset: assets/fonts/Cairo-Light.ttf
        - asset: assets/fonts/Cairo-Medium.ttf
        - asset: assets/fonts/Cairo-Regular.ttf
        - asset: assets/fonts/Cairo-SemiBold.ttf
    - family: Rubik
      fonts:
        - asset: assets/fonts/Rubik-Black.ttf
        - asset: assets/fonts/Rubik-BlackItalic.ttf
        - asset: assets/fonts/Rubik-Bold.ttf
        - asset: assets/fonts/Rubik-ExtraBold.ttf
        - asset: assets/fonts/Rubik-Light.ttf
        - asset: assets/fonts/Rubik-Medium.ttf
        - asset: assets/fonts/Rubik-Regular.ttf
        - asset: assets/fonts/Rubik-SemiBold.ttf
        - asset: assets/fonts/Rubik-Italic.ttf
        - asset: assets/fonts/Rubik-LightItalic.ttf
        - asset: assets/fonts/Rubik-SemiBoldItalic.ttf

flutter_intl:
  enabled: true
